[package]
name = "readme-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
typst = "0.15.1"
typst-assets = "0.15.1"
typst-layout = "0.15.1"
typst-svg = "0.15.1"
typst-kit = {
    version = "0.15.1",
    features = [
        "datetime",
        "embedded-fonts",
        "emit-diagnostics",
        "scan-fonts",
        "system-downloader",
        "system-files",
        "system-packages",
        "universe-packages",
    ]
}

axum = "0.8.9"
tokio = { version = "1.53.1", features = ["full"] }
